//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fiscal_Periods
    {
        public decimal Id { get; set; }
        public string Fiscal_PeriodName { get; set; }
        public string Fiscal_Year { get; set; }
        public string Fiscal_Month { get; set; }
        public string From_Month { get; set; }
        public string To_Month { get; set; }
        public Nullable<byte> Month_Status { get; set; }
        public byte Rec_Status { get; set; }
        public string InsUser { get; set; }
        public System.DateTime InsDate { get; set; }
        public int DaysNo { get; set; }
        public int NoOFDayInYear { get; set; }
    }
}
