//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_AccountPostingFormat
    {
        public decimal Internal_serial_Id { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public string TransType { get; set; }
        public string EntryType { get; set; }
        public string Actual_HireItem_Id { get; set; }
        public string CR_Type { get; set; }
        public string CR_Actual_HireItem_Id { get; set; }
        public string Dbt_Type { get; set; }
        public string Dbt_Actual_HireItem_Id { get; set; }
        public string Ins_User { get; set; }
        public Nullable<System.DateTime> Ins_Date { get; set; }
        public byte Rec_Status { get; set; }
    }
}
