//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_HireItemAccountAssign
    {
        public decimal Internal_serial_Id { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public string HireItem_Id { get; set; }
        public string AccountNo { get; set; }
        public byte AccountType { get; set; }
        public string Ins_User { get; set; }
        public Nullable<System.DateTime> Ins_date { get; set; }
    }
}
