//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GL_Integration_Segements
    {
        public int Internal_Serial { get; set; }
        public string Segment_Code_Field { get; set; }
        public string Segment_Code1_Field { get; set; }
        public string Segment_Code2_Field { get; set; }
        public string Segment_Code3_Field { get; set; }
        public string Segment_Code4_Field { get; set; }
        public string Segment_Code5_Field { get; set; }
        public string Segment_Code6_Field { get; set; }
    }
}
