//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_AccruedHireitem_Types
    {
        public string AccruedHireitem_Type_Id { get; set; }
        public string AccruedHireitem_Type_Name { get; set; }
        public string AccruedHireitem_Type_NameEn { get; set; }
        public byte Rec_Status { get; set; }
        public string AccruedHireItem_Id { get; set; }
    }
}
