//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_EmpAccruedOpenningBalance
    {
        public System.Guid Rec_Hdr_Id { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public decimal Emp_Serial_no { get; set; }
        public string Transdate { get; set; }
        public string MonthNo { get; set; }
        public decimal SalDailyPkg { get; set; }
        public decimal FixedPercntage { get; set; }
        public string Accrued_HireItem_Id { get; set; }
        public decimal HireItemValueBal { get; set; }
        public decimal DaysBal { get; set; }
        public decimal HireItemValueTransfer { get; set; }
        public decimal DaysTransfer { get; set; }
        public decimal HireItemValuePayed { get; set; }
        public decimal DaysPayed { get; set; }
        public decimal HireItemValueRemain { get; set; }
        public decimal DaysRemain { get; set; }
        public byte IsPosted { get; set; }
        public string Ins_User { get; set; }
        public Nullable<System.DateTime> Ins_Date { get; set; }
    }
}
