//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_EmpAllowanceRequest
    {
        public System.Guid Rec_Hdr_Id { get; set; }
        public decimal Rec_No { get; set; }
        public string ReferenceNo { get; set; }
        public string Request_Id { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public string Project_Id { get; set; }
        public decimal Emp_Serial_No { get; set; }
        public string TransDate { get; set; }
        public string FromDate { get; set; }
        public string ToDate { get; set; }
        public string Notes { get; set; }
        public string InsUser { get; set; }
        public System.DateTime InsDate { get; set; }
        public string Order_Status { get; set; }
        public string DocumentPath { get; set; }
        public decimal Commissioner_Serial_no { get; set; }
        public string MessageNotesForEmp { get; set; }
        public Nullable<decimal> Contract_Id { get; set; }
        public Nullable<decimal> ContractPeriod_Id { get; set; }
        public string Allowance_Type { get; set; }
        public string Allowance_Method_Type { get; set; }
        public string GradeJob_Id { get; set; }
        public string FromCity { get; set; }
        public string ToCity { get; set; }
        public Nullable<decimal> MissionDays { get; set; }
        public Nullable<decimal> DailyAllowance { get; set; }
        public Nullable<decimal> HousingAllowance { get; set; }
        public string TransportUsedType { get; set; }
        public Nullable<decimal> TransportAllowance { get; set; }
        public Nullable<byte> IsBookingFlight { get; set; }
        public Nullable<byte> IsSession { get; set; }
        public Nullable<decimal> ExpectedTotalValue { get; set; }
    
        public virtual Hr_Employees Hr_Employees { get; set; }
    }
}
