//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_EmpCustodies_History
    {
        public decimal Rec_No { get; set; }
        public Nullable<System.Guid> Hdr_Id { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public Nullable<decimal> Emp_Serial_No { get; set; }
        public Nullable<decimal> Emp_Serial_No_New { get; set; }
        public string Transdate { get; set; }
        public string Custody_Id { get; set; }
        public string Custody_Serial_No { get; set; }
        public Nullable<byte> Custody_Status { get; set; }
        public Nullable<byte> Custody_Status_New { get; set; }
        public string Custody_Desc { get; set; }
        public string Custody_Note { get; set; }
        public string Received_Date { get; set; }
        public string Ins_User { get; set; }
        public Nullable<System.DateTime> Ins_Date { get; set; }
    }
}
