//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_HiringMonthlyDuesPayment
    {
        public System.Guid Rec_Hdr_Id { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public decimal Emp_Serial_no { get; set; }
        public string TransDate { get; set; }
        public decimal HireItemValue { get; set; }
        public byte IsPosted { get; set; }
        public string Accrued_HireItem_Id { get; set; }
        public Nullable<decimal> Payed_Days { get; set; }
        public string MonthNo { get; set; }
        public string InsUser { get; set; }
        public Nullable<System.DateTime> InsDate { get; set; }
    }
}
