//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_MonthlyEmpActualAttendanceDays
    {
        public decimal Internal_serial_Id { get; set; }
        public string Company_Id { get; set; }
        public string Branch_Id { get; set; }
        public string Transdate { get; set; }
        public string Month_No { get; set; }
        public decimal Emp_Serial_No { get; set; }
        public Nullable<byte> MonthDaysNum { get; set; }
        public Nullable<byte> AttendsDaysNum { get; set; }
        public Nullable<byte> AnnualVacDaysNum { get; set; }
        public Nullable<byte> CompellingVacDaysNum { get; set; }
        public Nullable<byte> SickDasysNum { get; set; }
        public Nullable<byte> VacDaysNumWithoutSalary { get; set; }
        public Nullable<byte> OtherDaysNum { get; set; }
        public Nullable<byte> AbsenceDaysNum { get; set; }
        public Nullable<byte> DaysNumFromStartingContractInThisMonth { get; set; }
        public string InsUser { get; set; }
        public System.DateTime InsDate { get; set; }
        public Nullable<byte> Apporval_Status { get; set; }
        public Nullable<decimal> Contract_Id { get; set; }
        public Nullable<decimal> ContractPeriod_Id { get; set; }
        public Nullable<byte> CalculatedDaysNum { get; set; }
        public Nullable<decimal> OvertimePeriodByHour { get; set; }
        public Nullable<decimal> DelayPeriodByHour { get; set; }
    }
}
