//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hr_SecondmentTypes
    {
        public string SecondmentTypeId { get; set; }
        public string SecondmentTypeName { get; set; }
        public string SecondmentTypeNameEn { get; set; }
        public string HireItem_Id { get; set; }
        public Nullable<int> OrderRow { get; set; }
        public byte Rec_Status { get; set; }
    }
}
